# Author: Thomas Fischer
# License: MIT
# Description: GitHub Actions workflow for running tests on macOS and Raspberry Pi
# Version: 0.1.0
# Filename: test-workflow.yml
# Format: YAML

name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    
    - name: Run tests
      run: |
        python -m pytest tests/ --cov=./ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  test-raspberry-pi:
    name: Test on Raspberry Pi
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and run tests in ARM container
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm/v7
        file: ./Dockerfile.test
        push: false
        load: true
        tags: test-raspberrypi:latest

# You'll need to create a Dockerfile.test that sets up the environment and runs tests:
# FROM arm32v7/python:3.10-slim
# WORKDIR /app
# COPY . .
# RUN pip install -r requirements.txt
# RUN pip install -r requirements-dev.txt
# CMD ["python", "-m", "pytest", "tests/"]
